# These are configuration parameters that can be set by users
# The parameters enable access to the cloud collections

sources:
    OGH                     :
        s3_class            : ["ogh_cube", "stac_cube", "eo_cube",
                               "raster_cube"]
        service             : "STAC"
        rstac_version       : "1.0.0"
        url                 : "https://s3.eu-central-1.wasabisys.com/stac/openlandmap/landsat_glad.swa.ard2_bimonthly/collection.json"
        collections         :
            LANDSAT-GLAD-2M : &ogh_glad_2m
                bands       :
                    BLUE    : &ogh_landsat_blue
                        missing_value : 255
                        minimum_value : 0
                        maximum_value : 1
                        scale_factor  : 1
                        offset_value  : 0
                        resolution    :  30
                        band_name     : "blue_glad.landsat.ard2.swa_m_30m_s"
                        data_type     : "FLT4S"
                    GREEN    :
                        <<: *ogh_landsat_blue
                        band_name     : "green_glad.landsat.ard2.swa_m_30m_s"
                    RED     :
                        <<: *ogh_landsat_blue
                        band_name     : "red_glad.landsat.ard2.swa_m_30m_s"
                    NIR     :
                        <<: *ogh_landsat_blue
                        band_name     : "nir_glad.landsat.ard2.swa_m_30m_s"
                    SWIR1    :
                        <<: *ogh_landsat_blue
                        band_name     : "swir1_glad.landsat.ard2.swa_m_30m_s"
                    SWIR2    :
                        <<: *ogh_landsat_blue
                        band_name     : "swir2_glad.landsat.ard2.swa_m_30m_s"
                    THERMAL    :
                        <<: *ogh_landsat_blue
                        band_name     : "thermal_glad.landsat.ard2.swa_m_30m_s"
                satellite   : "LANDSAT"
                sensor      : "TM-ETM-OLI"
                platforms   :
                    LANDSAT-5: "landsat-5"
                    LANDSAT-7: "landsat-7"
                    LANDSAT-8: "landsat-8"
                collection_name : "landsat_glad.swa.ard2_bimonthly"
                open_data       : true
                open_data_token : false
                metadata_search : "tile"
                ext_tolerance   : 0.01
                grid_system     : "WRS-2"
                dates           : "1997 to 2022"
