# These are configuration parameters that can be set by users
# The parameters enable access to the cloud collections

sources:
    CDSE                    :
        s3_class            : ["cdse_cube", "stac_cube", "eo_cube",
                                "raster_cube"]
        service             : "STAC"
        url                 : "https://stac.dataspace.copernicus.eu/v1"
        collections         :
            SENTINEL-2-L2A  : &cdse_msi
                bands       :
                    B01     : &cdse_msi_60m
                        missing_value : 0
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : -0.1
                        resolution    : 60
                        band_name     : "B01_60m"
                        data_type     : "INT2U"
                    B02     : &cdse_msi_10m
                        missing_value : 0
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : -0.1
                        resolution    : 10
                        band_name     : "B02_10m"
                        data_type     : "INT2U"
                    B03     :
                        <<: *cdse_msi_10m
                        band_name     : "B03_10m"
                    B04     :
                        <<: *cdse_msi_10m
                        band_name     : "B04_10m"
                    B05     : &cdse_msi_20m
                        missing_value : 0
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : 0
                        resolution    : 20
                        band_name     : "B05_20m"
                        data_type     : "INT2U"
                    B06     :
                        <<: *cdse_msi_20m
                        band_name     : "B06_20m"
                    B07     :
                        <<: *cdse_msi_20m
                        band_name     : "B07_20m"
                    B08     :
                        <<: *cdse_msi_10m
                        band_name     : "B08_10m"
                    B8A     :
                        <<: *cdse_msi_20m
                        band_name     : "B8A_20m"
                    B09     :
                        <<: *cdse_msi_60m
                        band_name     : "B09_60m"
                    B11     :
                        <<: *cdse_msi_20m
                        band_name     : "B11_20m"
                    B12     :
                        <<: *cdse_msi_20m
                        band_name     : "B12_20m"
                    CLOUD   :
                        bit_mask      : false
                        band_name     : "SCL_20m"
                        values        :
                            0         : "missing_data"
                            1         : "defective pixel"
                            2         : "shadows"
                            3         : "cloud shadows"
                            4         : "vegetation"
                            5         : "non-vegetated"
                            6         : "water"
                            7         : "unclassified"
                            8         : "cloud medium"
                            9         : "cloud high"
                            10        : "thin cirrus"
                            11        : "snow or ice"
                        interp_values : [0, 1, 2, 3, 8, 9, 10]
                        resolution    :  20
                        data_type     : "INT1U"
                satellite   : "SENTINEL-2"
                sensor      : "MSI"
                platforms   :
                    SENTINEL-2A: "sentinel-2a"
                    SENTINEL-2B: "sentinel-2b"
                    SENTINEL-2C: "sentinel-2c"
                access_vars :
                    # Flags from: https://github.com/eu-cdse/notebook-samples/blob/main/stac/stac_ndvi.ipynb
                    AWS_HTTPS               : "YES"
                    AWS_VIRTUAL_HOSTING     : "FALSE"
                    AWS_S3_ENDPOINT         : "eodata.dataspace.copernicus.eu"
                    GDAL_HTTP_UNSAFESSL     : "YES"
                    GDAL_HTTP_TCP_KEEPALIVE : "YES"
                collection_name : "sentinel-2-l2a"
                open_data       : true
                open_data_token : true
                metadata_search : "tile"
                ext_tolerance   : 0
                grid_system     : "MGRS"
                item_type       : "S2MSI2A"
                dates           : "2015 to now"
