# These are configuration parameters that can be set by users
# The parameters enable access to the cloud collections

sources:
    MPC                     :
        s3_class            : ["mpc_cube", "stac_cube", "eo_cube",
                               "raster_cube"]
        service             : "STAC"
        rstac_version       : "1.0.0"
        url                 : "https://planetarycomputer.microsoft.com/api/stac/v1"
        token_url           : "https://planetarycomputer.microsoft.com/api/sas/v1/token"
        collections         :
            LANDSAT-C2-L2   : &mspc_oli
                bands       :
                    BLUE    : &mspc_oli_30m
                        missing_value : 0
                        minimum_value : 7273
                        maximum_value : 43636
                        scale_factor  : 0.0000275
                        offset_value  : -0.2
                        resampling    : "bilinear"
                        resolution    : 30
                        band_name     : "blue"
                        data_type     : "INT2U"
                    GREEN   :
                        <<: *mspc_oli_30m
                        band_name     : "green"
                    RED     :
                        <<: *mspc_oli_30m
                        band_name     : "red"
                    NIR08   :
                        <<: *mspc_oli_30m
                        band_name     : "nir08"
                    SWIR16  :
                        <<: *mspc_oli_30m
                        band_name     : "swir16"
                    SWIR22  :
                        <<: *mspc_oli_30m
                        band_name     : "swir22"
                    CLOUD   :
                        bit_mask      : true
                        band_name     : "qa_pixel"
                        values        :
                            0         : "Missing data"
                            1         : "Dilated Cloud"
                            2         : "High confidence cirrus"
                            3         : "High confidence cloud"
                            4         : "High confidence cloud shadow"
                            5         : "High confidence snow cover"
                            6         : "Clear"
                            7         : "Water"
                            8         : "Low/High confidence of cloud"
                            9         : "Medium/High confidence of cloud"
                            10        : "Low/High confidence of cloud shadow"
                            11        : "Medium/High confidence of cloud shadow"
                            12        : "Low/High confidence of snow"
                            13        : "Medium/High confidence of snow"
                            14        : "Low/High confidence of cirrus"
                            15        : "Medium/High confidence of cirrus"
                        interp_values : [0, 1, 2, 3, 4, 5, 9, 11, 13, 15]
                        resampling    : "near"
                        resolution    : 30
                        data_type     : "INT2U"
                satellite   : "LANDSAT"
                sensor      : "TM-ETM-OLI"
                platforms   :
                    LANDSAT-5: "landsat-5"
                    LANDSAT-7: "landsat-7"
                    LANDSAT-8: "landsat-8"
                    LANDSAT-9: "landsat-9"
                collection_name: "landsat-c2-l2"
                open_data: true
                open_data_token: false
                tile_required: false
                metadata_search : "feature"
                ext_tolerance: 0
                grid_system  : "WRS-2"
            SENTINEL-2-L2A  : &mspc_msi
                bands       :
                    B01     : &mspc_msi_60m
                        missing_value : -9999
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : 0
                        resolution   :  60
                        band_name     : "B01"
                        data_type     : "INT2S"
                    B02     : &mspc_msi_10m
                        missing_value : -9999
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : 0
                        resolution   :  10
                        band_name     : "B02"
                        data_type     : "INT2S"
                    B03     :
                        <<: *mspc_msi_10m
                        band_name     : "B03"
                    B04     :
                        <<: *mspc_msi_10m
                        band_name     : "B04"
                    B05     : &mspc_msi_20m
                        missing_value : -9999
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : 0
                        resolution   :  20
                        band_name     : "B05"
                        data_type     : "INT2S"
                    B06     :
                        <<: *mspc_msi_20m
                        band_name     : "B06"
                    B07     :
                        <<: *mspc_msi_20m
                        band_name     : "B07"
                    B08     :
                        <<: *mspc_msi_10m
                        band_name     : "B08"
                    B8A     :
                        <<: *mspc_msi_20m
                        band_name     : "B8A"
                    B09     :
                        <<: *mspc_msi_60m
                        band_name     : "B09"
                    B11     :
                        <<: *mspc_msi_20m
                        band_name     : "B11"
                    B12     :
                        <<: *mspc_msi_20m
                        band_name     : "B12"
                    CLOUD   :
                        bit_mask      : false
                        band_name     : "SCL"
                        values        :
                            0         : "missing_data"
                            1         : "defective pixel"
                            2         : "shadows"
                            3         : "cloud shadows"
                            4         : "vegetation"
                            5         : "non-vegetated"
                            6         : "water"
                            7         : "unclassified"
                            8         : "cloud medium"
                            9         : "cloud high"
                            10        : "thin cirrus"
                            11        : "snow or ice"
                        interp_values : [0, 1, 2, 3, 8, 9, 10, 11]
                        resolution   :  20
                        data_type     : "INT1U"
                satellite   : "SENTINEL-2"
                sensor      : "MSI"
                platforms   :
                    SENTINEL-2A: "Sentinel-2A"
                    SENTINEL-2B: "Sentinel-2B"
                collection_name: "sentinel-2-l2a"
                open_data: true
                open_data_token: false
                metadata_search : "tile"
                ext_tolerance: 0
                grid_system  : "MGRS"
            SENTINEL-1-GRD  : &mspc_s1_grd
                bands       :
                    VV      : &mspc_grd_10m
                        missing_value : 0
                        minimum_value : 1
                        maximum_value : 65534
                        scale_factor  : 0.001
                        offset_value  : 0
                        resolution    : 10
                        band_name     : "vv"
                        data_type     : "INT2U"
                    VH     :
                        <<: *mspc_grd_10m
                        band_name     : "vh"
                satellite   : "SENTINEL-1"
                sensor      : "C-band-SAR"
                orbits      : ["ascending", "descending"]
                platforms   :
                    SENTINEL-1A: "Sentinel-1A"
                    SENTINEL-1B: "Sentinel-1B"
                collection_name: "sentinel-1-grd"
                sar_cube: true
                open_data: true
                open_data_token: false
                metadata_search: "feature"
                ext_tolerance: 0
                grid_system : "MGRS"
            SENTINEL-1-RTC  : &mspc_s1_rtc
                bands       :
                    VV      : &mspc_rtc_10m
                        missing_value : -32768.0
                        minimum_value : 0
                        maximum_value : 65534
                        scale_factor  : 1
                        offset_value  : 0
                        resolution    : 10
                        band_name     : "vv"
                        data_type     : "FLT4S"
                    VH     :
                        <<: *mspc_rtc_10m
                        band_name     : "vh"
                satellite   : "SENTINEL-1"
                sensor      : "C-band-SAR"
                orbits      : ["ascending", "descending"]
                platforms   :
                    SENTINEL-1A: "Sentinel-1A"
                    SENTINEL-1B: "Sentinel-1B"
                collection_name: "sentinel-1-rtc"
                sar_cube: true
                open_data: false
                open_data_token: false
                metadata_search: "feature"
                ext_tolerance: 0
                grid_system : "MGRS"
                token_vars  :  ["MPC_TOKEN"]

