# These are configuration parameters that can be set by users
# The parameters enable access to the cloud collections

sources:
    SDC                     :
        s3_class            : ["sdc_cube", "stac_cube", "eo_cube",
                               "raster_cube"]
        service             : "STAC"
        url                 : "https://explorer.swissdatacube.org/stac"
        collections         :
            S2_L2A_10M_SWISS: &swiss_s2
                bands       :
                    B01     : &swiss_msi_10m
                        missing_value : -9999
                        minimum_value : 0
                        maximum_value : 10000
                        scale_factor  : 0.0001
                        offset_value  : 0
                        resolution    :  10
                        band_name     : "B01"
                        data_type     : "INT2S"
                    B02     :
                        <<: *swiss_msi_10m
                        band_name     : "B02"
                    B03     :
                        <<: *swiss_msi_10m
                        band_name     : "B03"
                    B04     :
                        <<: *swiss_msi_10m
                        band_name     : "B04"
                    B05     :
                        <<: *swiss_msi_10m
                        band_name     : "B05"
                    B06     :
                        <<: *swiss_msi_10m
                        band_name     : "B06"
                    B07     :
                        <<: *swiss_msi_10m
                        band_name     : "B07"
                    B08     :
                        <<: *swiss_msi_10m
                        band_name     : "B08"
                    B8A     :
                        <<: *swiss_msi_10m
                        band_name     : "B8A"
                    B09     :
                        <<: *swiss_msi_10m
                        band_name     : "B09"
                    B11     :
                        <<: *swiss_msi_10m
                        band_name     : "B11"
                    B12     :
                        <<: *swiss_msi_10m
                        band_name     : "B12"
                    CLOUD   :
                        bit_mask      : false
                        band_name     : "SCL"
                        values        :
                            0         : "missing_data"
                            1         : "defective pixel"
                            2         : "shadows"
                            3         : "cloud shadows"
                            4         : "vegetation"
                            5         : "non-vegetated"
                            6         : "water"
                            7         : "unclassified"
                            8         : "cloud medium"
                            9         : "cloud high"
                            10        : "thin cirrus"
                            11        : "snow or ice"
                        interp_values : [0, 1, 2, 3, 8, 9, 10]
                        resolution   :  20
                        data_type     : "INT1U"
                satellite   : "SENTINEL-2"
                sensor      : "MSI"
                collection_name: "s2_l2"
                open_data: true
                open_data_token: false
                metadata_search : "feature"
                ext_tolerance: 0
                grid_system  : "MGRS"
