# These are configuration parameters that can be set by users
# The parameters enable access to the cloud collections

sources:
    AWS                     :
        s3_class            : ["aws_cube", "stac_cube", "eo_cube",
                               "raster_cube"]
        service             : "STAC"
        url                 : "https://earth-search.aws.element84.com/v1/"
        collections         :
            SENTINEL-2-L2A  :
                bands       :
                    B01     : &aws_msi_60m
                        missing_value: -9999
                        minimum_value: 0
                        maximum_value: 10000
                        scale_factor : 0.0001
                        offset_value : 0
                        resolution  :  60
                        band_name    : "coastal"
                        data_type     : "INT2S"
                    B02     : &aws_msi_10m
                        missing_value: -9999
                        minimum_value: 0
                        maximum_value: 10000
                        scale_factor : 0.0001
                        offset_value : 0
                        resolution  :  10
                        band_name    : "blue"
                        data_type     : "INT2S"
                    B03     :
                        <<: *aws_msi_10m
                        band_name    : "green"
                    B04     :
                        <<: *aws_msi_10m
                        band_name    : "red"
                    B05     : &aws_msi_20m
                        missing_value: -9999
                        minimum_value: 0
                        maximum_value: 10000
                        scale_factor : 0.0001
                        offset_value : 0
                        resolution  :  20
                        band_name    : "rededge1"
                        data_type     : "INT2S"
                    B06     :
                        <<: *aws_msi_20m
                        band_name    : "rededge2"
                    B07     :
                        <<: *aws_msi_20m
                        band_name    : "rededge3"
                    B08     :
                        <<: *aws_msi_10m
                        band_name    : "nir"
                    B8A     :
                        <<: *aws_msi_20m
                        band_name    : "nir08"
                    B09     :
                        <<: *aws_msi_60m
                        band_name    : "nir09"
                    B11     :
                        <<: *aws_msi_20m
                        band_name    : "swir16"
                    B12     :
                        <<: *aws_msi_20m
                        band_name    : "swir22"
                    CLOUD   :
                        bit_mask     : false
                        band_name    : "scl"
                        values       :
                            0        : "missing_data"
                            1        : "defective pixel"
                            2        : "shadows"
                            3        : "cloud shadows"
                            4        : "vegetation"
                            5        : "non-vegetated"
                            6        : "water"
                            7        : "unclassified"
                            8        : "cloud medium"
                            9        : "cloud high"
                            10       : "thin cirrus"
                            11       : "snow or ice"
                        interp_values: [0, 1, 2, 3, 8, 9, 10, 11]
                        resolution  : 20
                        data_type     : "INT1U"
                satellite   : "SENTINEL-2"
                sensor      : "MSI"
                platforms   :
                    SENTINEL-2A: "sentinel-2a"
                    SENTINEL-2B: "sentinel-2b"
                collection_name: "sentinel-2-l2a"
                access_vars :
                   AWS_DEFAULT_REGION   : "us-west-2"
                   AWS_S3_ENDPOINT      : "s3.amazonaws.com"
                   AWS_NO_SIGN_REQUEST  : true
                open_data       : true
                open_data_token : false
                metadata_search : "tile"
                ext_tolerance   : 0
                grid_system     : "MGRS"
                dates           : "2015 to now"
            SENTINEL-S2-L2A-COGS :
                bands       :
                    B01     : &aws_cog_msi_60m
                        missing_value: -9999
                        minimum_value: 0
                        maximum_value: 10000
                        scale_factor : 0.0001
                        offset_value : 0
                        resolution   : 60
                        band_name    : "coastal"
                        data_type    : "INT2S"
                    B02     : &aws_cog_msi_10m
                        missing_value: -9999
                        minimum_value: 0
                        maximum_value: 10000
                        scale_factor : 0.0001
                        offset_value : 0
                        resolution  :  10
                        band_name    : "blue"
                        data_type    : "INT2S"
                    B03     :
                        <<: *aws_cog_msi_10m
                        band_name    : "green"
                    B04     :
                        <<: *aws_cog_msi_10m
                        band_name    : "red"
                    B05     : &aws_cog_msi_20m
                        missing_value: -9999
                        minimum_value: 0
                        maximum_value: 10000
                        scale_factor : 0.0001
                        offset_value : 0
                        resolution  :  20
                        band_name    : "rededge1"
                        data_type    : "INT2S"
                    B06     :
                        <<: *aws_cog_msi_20m
                        band_name    : "rededge2"
                    B07     :
                        <<: *aws_cog_msi_20m
                        band_name    : "rededge3"
                    B08     :
                        <<: *aws_cog_msi_10m
                        band_name    : "nir"
                    B8A     :
                        <<: *aws_cog_msi_20m
                        band_name    : "nir08"
                    B09     :
                        <<: *aws_cog_msi_60m
                        band_name    : "nir09"
                    B11     :
                        <<: *aws_cog_msi_20m
                        band_name    : "swir16"
                    B12     :
                        <<: *aws_cog_msi_20m
                        band_name    : "swir22"
                    CLOUD   :
                        bit_mask     : false
                        band_name    : "SCL"
                        values       :
                            0        : "missing_data"
                            1        : "defective pixel"
                            2        : "shadows"
                            3        : "cloud shadows"
                            4        : "vegetation"
                            5        : "non-vegetated"
                            6        : "water"
                            7        : "unclassified"
                            8        : "cloud medium"
                            9        : "cloud high"
                            10       : "thin cirrus"
                            11       : "snow or ice"
                        interp_values: [0, 1, 2, 3, 7, 8, 9, 10, 11]
                        resolution  :  20
                        data_type    : "INT1U"
                satellite   : "SENTINEL-2"
                sensor      : "MSI"
                platforms   :
                    SENTINEL-2A: "sentinel-2a"
                    SENTINEL-2B: "sentinel-2b"
                collection_name: "sentinel-2-l2a"
                access_vars :
                    AWS_DEFAULT_REGION   : "us-west-1"
                    AWS_S3_ENDPOINT      : "s3.amazonaws.com"
                    AWS_NO_SIGN_REQUEST  : true
                open_data: true
                open_data_token: false
                metadata_search: "tile"
                review_dates: ["2020-08-16"]
                ext_tolerance: 0
                grid_system  : "MGRS"
                dates        : "2015 to now"
            LANDSAT-C2-L2   : &aws_oli
                bands       :
                    BLUE : &aws_oli_30m
                        missing_value : 0
                        minimum_value : 7273
                        maximum_value : 43636
                        scale_factor  : 0.0000275
                        offset_value  : -0.2
                        resampling    : "bilinear"
                        resolution    : 30
                        band_name     : "blue"
                        data_type     : "INT2U"
                    GREEN   :
                        <<: *aws_oli_30m
                        band_name     : "green"
                    RED     :
                        <<: *aws_oli_30m
                        band_name     : "red"
                    NIR08   :
                        <<: *aws_oli_30m
                        band_name     : "nir08"
                    SWIR16  :
                        <<: *aws_oli_30m
                        band_name     : "swir16"
                    SWIR22  :
                        <<: *aws_oli_30m
                        band_name     : "swir22"
                    CLOUD   :
                        bit_mask      : true
                        band_name     : "qa_pixel"
                        values        :
                            0         : "Missing data"
                            1         : "Dilated Cloud"
                            2         : "High confidence cirrus"
                            3         : "High confidence cloud"
                            4         : "High confidence cloud shadow"
                            5         : "High confidence snow cover"
                            6         : "Clear"
                            7         : "Water"
                            8         : "Low/High confidence of cloud"
                            9         : "Medium/High confidence of cloud"
                            10        : "Low/High confidence of cloud shadow"
                            11        : "Medium/High confidence of cloud shadow"
                            12        : "Low/High confidence of snow"
                            13        : "Medium/High confidence of snow"
                            14        : "Low/High confidence of cirrus"
                            15        : "Medium/High confidence of cirrus"
                        interp_values : [0, 1, 2, 3, 4, 5, 9, 11, 13, 15]
                        resampling    : "near"
                        resolution    : 30
                        data_type     : "INT2U"
                satellite   : "LANDSAT"
                sensor      : "TM-ETM-OLI"
                platforms   :
                    LANDSAT-5: "landsat-5"
                    LANDSAT-7: "landsat-7"
                    LANDSAT-8: "landsat-8"
                    LANDSAT-9: "landsat-9"
                collection_name: "landsat-c2-l2"
                access_vars :
                   AWS_DEFAULT_REGION   : "us-west-2"
                   AWS_S3_ENDPOINT      : "s3.amazonaws.com"
                   AWS_REQUEST_PAYER    : "requester"
                   AWS_NO_SIGN_REQUEST  : false
                open_data   : false
                open_data_token: false
                metadata_search : "feature"
                ext_tolerance: 0
                grid_system  : "WRS-2"
                dates        : "1982 to now"
