processing_bloat        : 8
rstac_pagination_limit  : 100
gdal_creation_options   : ["COMPRESS=LZW", "BIGTIFF=YES"]

colors:
    Cropland:           "khaki"
    Deforestation:      "sienna"
    Forest :            "darkgreen"
    Grassland :         "lightgreen"
    NonForest:          "lightsteelblue1"
