# Internal configuration parameters - relevant only to sits developers
# s3 classes known to sits
sits_s3_classes :   ["sits", "patterns", "predicted", "sits_model",
                    "sits_cube", "raster_cube", "probs_cube",
                    "uncertainty_cube", "classified_image",
                    "stac_cube", "bdc_cube", "aws_cube",
                    "usgs_cube", "deafrica_cube"]

# s3 classes resulting from classification and post-classification
sits_s3_classes_proc :   ["probs_cube","uncertainty_cube", "classified_image"]

# bands resulting from classification and post-classification
sits_results_bands : ["probs", "bayes", "bilat", "gauss", "uncert",
                      "entropy", "class"]

# bands resulting from classification and post-classification
sits_results_s3_class:
                    probs: "probs_cube"
                    bayes: "probs_cube"
                    bilat: "probs_cube"
                    gauss: "probs_cube"
                    uncert: "uncertainty_cube"
                    entropy: "uncertainty_cube"
                    class:  "classified_image"

# parsing info contents for results cube
results_parse_info_def : ["X1", "X2", "tile", "start_date", "end_date",
"band", "version"]
results_parse_info_col : ["tile", "start_date", "end_date", "band"]

# mandatory columns in data cube description
sits_cube_cols :    ["source", "collection", "satellite", "sensor",
"tile", "bands", "xmin", "xmax", "ymin", "ymax",
"crs", "labels"]

# mandatory columns in tibble description
sits_tibble_cols :  ["longitude", "latitude", "start_date",
"end_date", "label", "cube",
"time_series"]

# mandatory columns in predicted time series classification
ts_predicted_cols:  ["from", "to", "class"]

# supported user sample file formats
sample_file_formats : ["csv", "shp"]

# supported user sample object formats for "sits_get_data"
sample_get_data_formats : ["data.frame", "tbl_df", "sf", "sits"]

# mandatory columns in CSV input files
df_sample_columns : ["longitude", "latitude", "start_date", "end_date", "label"]

# possible som evaluations
som_outcomes    : ["clean", "analyze", "remove"]

# supported shp types
sf_geom_types_supported : ["POINT", "POLYGON", "MULTIPOLYGON"]

# local cube config options
local_s3_class          : ["local_cube", "raster_cube"]
local_file_extensions   : ["tiff", "tif", "jp2", "hdf", "vrt"]
local_parse_info_col    : ["tile", "band", "date"]
local_parse_info_def    : ["X1", "X2", "tile", "band", "date"]

# default configuration for raster cubes
raster_cube_scale_factor : 0.0001
raster_cube_data_type    : "INT2S"
raster_cube_offset_value : 0
raster_cube_missing_value : -9999
raster_cube_minimum_value : -10000
raster_cube_maximum_value : 10000

# configuration for generate tokens for mpc cubes
cube_token_generator_n_tries: 3

# configuration for probability cubes
probs_cube_scale_factor : 0.0001
probs_cube_data_type    : "INT2U"

# configuration for classified cubes
class_cube_data_type    : "INT1U"

# minimum number of files for sits local cube to be run on parallel
local_min_files_for_parallel : 20

# valid raster data types
valid_raster_data_types : ["INT1U", "INT2U", "INT2S", "INT4U",
                          "INT4S", "FLT4S", "FLT8S"]

# valid raster resampling methods
valid_raster_resampling : ["near", "bilinear", "cubic",
                          "cubicspline", "lanczos"]

# deep learning activation methods
dl_activation_methods : ["relu", "elu", "selu", "sigmoid"]

# metadata search strategy
metadata_search_strategies : ["tile", "feature"]

# class interval methods for plotting
class_intervals: ["sd", "equal", "quantile", "log", "pretty"]

# parse info of generated regular cubes
reg_file_parse_info: ["cube", "tile", "band", "date"]

# gdalcubes parameters
gdalcubes_chunk_size: [1, 2048, 2048]
gdalcubes_type_format: "int16"
gdalcubes_cog_generate: true
gdalcubes_cog_resample_overview: "bilinear"

# uncertainty window function
uncertainty_window_functions:
    median: "stats::median"
