# Internal configuration parameters - relevant only to sits developers
# default raster package
raster_api_package      : "terra"

# default vector package
vector_api_package      : "sf"

# sample size
summary_sample_size : 10000

# get data strategy
n_samples_to_split: 1000

# estimated relative growth size of R memory relative to block size
processing_bloat        : 5
processing_bloat_cpu    : 5
processing_bloat_smooth : 8
processing_bloat_seg    : 2
processing_bloat_gpu    : 2

# number of items returned by stac service
rstac_pagination_limit  : 100

# configuration for generate tokens for mpc cubes
cube_token_generator_n_tries: 3
cube_token_generator_sleep_time: 10
cube_token_generator_min_remaining_time: 5

# mandatory columns in data cube description
sits_cube_cols :    ["source", "collection", "satellite", "sensor",
"tile", "xmin", "xmax", "ymin", "ymax", "crs", "file_info"]

# mandatory columns in tibble description
sits_tibble_cols :  ["longitude", "latitude", "start_date",
"end_date", "label", "cube", "time_series"]

# mandatory columns in predicted time series classification
ts_predicted_cols:  ["from", "to", "class"]

# supported user sample file formats
sample_file_formats : ["csv", "shp"]

# supported user sample object formats for "sits_get_data"
sample_get_data_formats : ["data.frame", "tbl_df", "sf", "sits"]

# mandatory columns in CSV input files
df_sample_columns : ["longitude", "latitude", "start_date", "end_date", "label"]

# supported shp types
sf_geom_types_supported : ["POINT", "POLYGON", "MULTIPOLYGON"]

# local cube config options
local_s3_class          : ["local_cube", "raster_cube"]
local_file_extensions   : ["tiff", "tif", "jp2", "hdf", "vrt", "gpkg"]
local_parse_info_col    : ["tile", "band", "date"]
local_parse_info_def    : ["X1", "X2", "tile", "band", "date"]

# parse info of generated regular cubes
reg_file_parse_info: ["cube", "tile", "band", "date"]

# parsing info contents for results cube
results_parse_info_def : ["X1", "X2", "tile", "start_date", "end_date",
"band", "version"]
results_parse_info_col : ["tile", "start_date", "end_date", "band"]

# bands resulting from classification and post-classification
sits_results_bands : ["probs", "bayes", "uncert", "entropy",
                      "class", "least", "margin", "variance",
                      "segments"]

# bands resulting from classification and smoothing
sits_probs_bands : ["probs", "bayes"]
# bands resulting from uncertainty
sits_uncert_bands : ["uncert", "entropy", "least", "margin"]

# bands resulting from classification and post-classification
sits_results_s3_class:
                    probs: "probs_cube"
                    probs-vector: "probs_vector_cube"
                    bayes: "probs_cube"
                    uncert: "uncertainty_cube"
                    entropy: "uncertainty_cube"
                    variance: "variance_cube"
                    class:  "class_cube"
                    class-vector:  "class_vector_cube"

# default configuration for raster cubes
raster_cube_scale_factor : 0.0001
raster_cube_data_type    : "INT2S"
raster_cube_offset_value : 0
raster_cube_missing_value : -9999
raster_cube_minimum_value : -10000
raster_cube_maximum_value : 10000

# old configuration for probability cubes
probs_cube_scale_factor : 0.0001
probs_cube_data_type    : "INT2U"
probs_cube_missing_value: 65535
probs_cube_band         : "probs"
probs_cube_class        : ["probs_cube", "raster_cube", "sits_cube", "tbl_df",
                           "tbl", "data.frame"]

# Default values for non-registered bands
default_values       :
    eo_cube          :
        data_type    : "INT2S"
        missing_value: -32768
        minimum_value: -10000
        maximum_value: 10000
        offset_value : 0
        scale_factor : 0.0001

# Derived cube definitions
derived_cube         :
    probs_cube       :
        s3_class     : [ "probs_cube", "derived_cube", "raster_cube" ]
        bands        :
            probs    : &int2u_0_10000
                data_type    : "INT2U"
                missing_value: 65535
                minimum_value: 1
                maximum_value: 10000
                offset_value : 0
                scale_factor : 0.0001
            bayes    :
                <<: *int2u_0_10000
    variance_cube       :
        s3_class     : [ "variance_cube", "derived_cube", "raster_cube" ]
        bands        :
            variance :
                data_type    : "INT2U"
                missing_value: 65535
                minimum_value: 1
                maximum_value: 10000
                offset_value : 0
                scale_factor : 0.01
    uncertainty_cube :
        s3_class     : [ "uncertainty_cube", "derived_cube", "raster_cube" ]
        bands        :
            least    :
                <<: *int2u_0_10000
            entropy  :
                <<: *int2u_0_10000
            margin   :
                <<: *int2u_0_10000
    class_cube       :
        s3_class     : [ "class_cube", "derived_cube", "raster_cube" ]
        bands        :
            class    :
                data_type    : "INT1U"
                missing_value: 255
                minimum_value: 0
                maximum_value: 254
                offset_value : 0
                scale_factor : 1

# Vector cube definitions
vector_cube          :
    segs_cube        :
        s3_class     : ["segs_cube", "vector_cube"]
        bands        :
            segments :
    probs_vector_cube:
        s3_class     : ["probs_vector_cube", "derived_vector_cube", "segs_cube",
                        "vector_cube"]
        bands        :
            probs-vector :
    class_vector_cube:
        s3_class     : ["class_vector_cube", "derived_vector_cube", "segs_cube",
                        "vector_cube"]
        bands        :
            class-vector    :

# configuration for classified cubes
class_cube_data_type    : "INT1U"
class_cube_missing_value: 255

# minimum number of files for sits local cube to be run on parallel
local_min_files_for_parallel : 20

# valid raster data types
valid_raster_data_types : ["INT1U", "INT2U", "INT2S", "INT4U",
                          "INT4S", "FLT4S", "FLT8S"]

# valid raster resampling methods
valid_raster_resampling : ["near", "bilinear", "cubic",
                          "cubicspline", "lanczos"]

# GDAL GTiff presets
gdal_presets         :
    cog              :
        overviews    : [2, 4, 8, 16]
        method       : "NEAREST"
    block            :
        of           : "GTiff"
        co           : ["COMPRESS=NONE", "BIGTIFF=NO"] # cannot be tiled!
    image            :
        of           : "GTiff"
        co           : ["COMPRESS=LZW", "PREDICTOR=2", "BIGTIFF=YES",
                        "TILED=YES", "BLOCKXSIZE=512", "BLOCKYSIZE=512"]

# GDAL GTiff default creation options
gdal_creation_options   : [ "COMPRESS=LZW", "PREDICTOR=2",
                            "BIGTIFF=YES", "TILED=YES",
                            "BLOCKXSIZE=512", "BLOCKYSIZE=512" ]

gdalcubes_options       : ["COMPRESS=LZW", "PREDICTOR=2",
                           "BIGTIFF=YES", "BLOCKXSIZE=512",
                           "BLOCKYSIZE=512"]
# gdalcubes parameters
gdalcubes_chunk_size: [1, 2048, 2048]
gdalcubes_type_format: "int16"
gdalcubes_cog_generate: true
gdalcubes_cog_resample_overview: "bilinear"

# dendrogram parameters
dendro_dist_method: ["dtw", "dtw2", "dtw_basic", "lbk", "lbi"]
dendro_linkage: ["ward.D", "ward.D2", "single", "complete",
                 "average", "mcquitty", "median", "centroid"]

# possible som evaluations
som_outcomes    : ["clean", "analyze", "remove"]

# deep learning activation methods
dl_activation_methods : ["relu", "elu", "selu", "sigmoid"]

# metadata search strategy
metadata_search_strategies : ["tile", "feature"]


# Colours and plots
#
# class interval methods for plotting
class_intervals: ["sd", "equal", "quantile", "log", "pretty"]
# color table mandatory collumns
sits_color_table_cols: ["name", "color"]
# maxbytes per plot (in MB)
plot_max_Mbytes: 10

# tmap configurations
tmap:
        max_cells: 1e+06
        graticules_labels_size: 0.7
        legend_outside: False
        legend_outside_position: "right"
        legend_title_size: 1.0
        legend_text_size: 1.0
        legend_bg_color: "white"
        legend_bg_alpha: 0.5
        legend_width: 0.5
        legend_position: ["left", "bottom"]
        legend_height: 1.0
        scale: 0.5
        font_family: "plex_sans"

# maxbytes for leaflet (in MB)
leaflet_megabytes : 64
leaflet_min_megabytes : 16
leaflet_max_megabytes : 512
# estimated compression factor for leaflet
leaflet_comp_factor : 0.50
